import { Button, Carousel } from 'antd';
import { Inter } from 'next/font/google';
import Head from 'next/head';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  console.log('test');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Button>stsd</Button>
        <Carousel style={{ width: '100px' }}>
          <div>1</div>
          <div>2</div>
          <div>3</div>
        </Carousel>
      </main>
    </>
  );
}
